// <auto-generated />
using System;
using Cotton.Sync.App.State;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cotton.Sync.App.State.Migrations
{
    [DbContext(typeof(SyncAppDbContext))]
    [Migration("20260607084529_AddSyncPausedPreference")]
    partial class AddSyncPausedPreference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Cotton.Sync.App.Preferences.AppPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("EnableNotifications")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable_notifications");

                    b.Property<bool>("IsSyncPaused")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_sync_paused");

                    b.Property<string>("RememberedServerUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT")
                        .HasColumnName("remembered_server_url");

                    b.Property<string>("RememberedUsername")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasColumnName("remembered_username");

                    b.Property<bool>("StartMinimizedToTray")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_minimized_to_tray");

                    b.Property<bool>("StartWithOperatingSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("start_with_operating_system");

                    b.Property<int>("ThemeMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("theme_mode");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("app_preferences");
                });

            modelBuilder.Entity("Cotton.Sync.App.SyncPairs.SyncPairSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LocalRootPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_root_path");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mode");

                    b.Property<string>("RemoteDisplayPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_display_path");

                    b.Property<Guid>("RemoteRootNodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_root_node_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.ToTable("sync_pair_settings");
                });
#pragma warning restore 612, 618
        }
    }
}
