// <auto-generated />
using System;
using Cotton.Sync.State;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cotton.Sync.State.Migrations
{
    [DbContext(typeof(SyncStateDbContext))]
    [Migration("20260602175534_InitialSyncState")]
    partial class InitialSyncState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Cotton.Sync.State.SyncStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("kind");

                    b.Property<string>("LocalContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("local_content_hash");

                    b.Property<DateTime?>("LocalLastWriteUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("local_last_write_utc");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path");

                    b.Property<string>("RelativePathKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("relative_path_key");

                    b.Property<string>("RemoteContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_content_hash");

                    b.Property<string>("RemoteETag")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_etag");

                    b.Property<Guid?>("RemoteFileId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_file_id");

                    b.Property<Guid?>("RemoteNodeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("remote_node_id");

                    b.Property<string>("SyncPairId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("sync_pair_id");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("synced_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RemoteFileId");

                    b.HasIndex("RemoteNodeId");

                    b.HasIndex("SyncPairId", "RelativePathKey")
                        .IsUnique();

                    b.ToTable("sync_entries");
                });
#pragma warning restore 612, 618
        }
    }
}
